### ISSUE TITLE
JRA football mobile site

### ISSUE THREAD

**Issue by GoogleCodeExporter** [StillMooing/stillmooingfootball#14]
```
JRA football needs a mobile site... This will be targeted for a 2012 football 
season limited release.

```

Original issue reported on code.google.com by `jjud...@gmail.com` on 14 Jan 2012 at 11:53

**Comment by StillMooing** [comment]
Progress is continuing... Has an icon and "mobile-app" ability and will stick with this functionality for now.

Need to fix/add more issues for basic functionality

**Comment by StillMooing** [comment]
Closing out issue... This is a largely functioning V1 now... Future bugs and enhancements will be own issue
