### ISSUE TITLE
Add ability to comment on blog entries

### ISSUE THREAD

**Issue by GoogleCodeExporter** [StillMooing/stillmooingfootball#19]
```
This should be relatively easy... Should we re-write blog entry code to force 
separate entries in db for each entry so can comment on them individually?
```

Original issue reported on code.google.com by `jjud...@gmail.com` on 15 Jan 2012 at 12:02

**Comment by StillMooing** [comment]
This has actually been done since the beginning of the 2014 year.  Blogs have been moved to individual entries per blog, comment-ability added, ordering added as well as improvements to adding pictures...
