### ISSUE TITLE
Need a Super Admin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [StillMooing/stillmooingfootball#21]
```
In order to avoid mucking in the db entirely, need to figure out how to make a 
Super Admin that can make alterations cross-year to allow for first Admin of 
year to be tagged as Admin


```

Original issue reported on code.google.com by `jud...@stillmooing.com` on 9 Mar 2013 at 8:45

**Comment by StillMooing** [comment]
Note:  If the db is ever re-written to have one login per person with multiple user names, that would solve this...

**Comment by StillMooing** [comment]
2017 -- SetupYear now creates Admin account... prove out in 2018, then close issue.

**Comment by StillMooing** [comment]
Working as intended
