### ISSUE TITLE
Date in enterSchedule not "dummy-proof"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [StillMooing/stillmooingfootball#7]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


Please use labels and text to provide additional information.


```

Original issue reported on code.google.com by `jjud...@gmail.com` on 5 Aug 2008 at 1:27

**Comment by StillMooing** [comment]
This now auto-pulls from NFL XML.  Still susceptible to in-season editing...

Prove out in 2018 and then decide whether to maintain issue for fool-proofing, or call it good enough...

**Comment by StillMooing** [comment]
Works great pulling from NFL XML... Rest is a corner-case... Let's call this good
